#smtp mail properties
mail:
  smtp:
    auth: true
    starttlsEnable: true
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    protocol: smtp
    senderName: Test Test
    senderEmail: stonebstonesteel@gmail.com
